name: banking-mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
      - torch 
      - numpy 
      - pandas
      - matplotlib
      - seaborn 
      - scikit-learn 
      - pyyaml 
      - tqdm 
      - transformers
      - mlflow
      - jinja2
      - flask
      - setuptools
      - streamlit
      - graphviz
      - psutil
      - arize
      - pytest
