artifact_location: file:///Users/hoangthuyduongvu/Desktop/sda_mlops/src/models/mlruns_perceptron/986589959954045561
creation_time: 1742671802426
experiment_id: '986589959954045561'
last_update_time: 1742671802426
lifecycle_stage: active
name: perceptron
