name: Deploy to Cloud Run

env:
  # SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }} 
  # PROJECT_ID: ${{ secrets.GCP_SA_KEY }}
  SERVICE_NAME:  banking-mlops-app
  PROJECT_ID: appmod-demo-lvl
  DOCKER_IMAGE_URL: ${{ secrets.GCP_REGION }}-docker.pkg.dev/$PROJECT_ID/SERVICE_NAME/mlops-app

on:
  push:
    branches:
      - cyrena-cd

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

  job_id:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: $PROJECT_ID

      - name: Set GCP project 
        run: |
          echo "PROJECT_ID: $PROJECT_ID"  # Add this line
          gcloud config set project $PROJECT_ID

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKER_IMAGE_URL:latest -f Dockerfile.prod .
          docker push $DOCKER_IMAGE_URL:latest

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME $SERVICE_NAME
          gcloud run deploy $SERVICE_NAME \
            --image $DOCKER_IMAGE_URL:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated